### ISSUE TITLE
Dynamically creating 

### ISSUE THREAD

**Issue by ZichKoding** [ZichKoding/TuneItUp#5]
# **Description**

- Move search bar closer to header
- On the left side of the page display past/future events 
- On right side of the page album cover
- Underneath the album cover display the music video.

**Comment by ZichKoding** [comment]
@Brock-Merritt 
There are 3 main lines of code to display the past and future events. I added a `.testingContainer`  to the CSS to make it visible. 

I'll start working on turning this into a function tomorrow and add more list items to it.

**Comment by ZichKoding** [comment]
@Brock-Merritt 
I've pushed the 3 main containers up. Don't have the updated HTML and CSS yet, but got the main part finished. I'm going to move onto the data endpoints until we have the updated HTML & CSS.

**Comment by Brock-Merritt** [comment]
I'll work on them as soon as I can, I got stuck up on the Javascript for
chapter 6 today and have been preparing for my weekly 8 am Sunday meeting.
Saturdays are usually busy, but I will help in literally any way I can

**Comment by ZichKoding** [comment]
No problem I'm leaving these comments here so you know where I left off and to help me stay organized.

**Comment by Brock-Merritt** [comment]
I should get done with this meeting at 11 or noon, will get to them as soon
as I can

**Comment by ZichKoding** [comment]
No worries man I'm going through the API's and trying to find the endpoints needed.
